name: Test & Deploy

on:
  push:
    branches:
      - staging

jobs:
  tests:
    name: Tests
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pnpm

      - name: Test
        run: pnpm test

  deploy:
    name: Deploy
    needs: tests
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses:
          with:
            
